### ISSUE TITLE
Text is in the same color as a background

### ISSUE THREAD

**Issue by dzon2000** [brx19/slack-night-mode#2]
First screenshot shows the place where text is the same color as a background.

![image](https://user-images.githubusercontent.com/33714273/45488338-64768600-b761-11e8-923a-60ab3deb8a7a.png)

Desired result:

![image](https://user-images.githubusercontent.com/33714273/45488405-9b4c9c00-b761-11e8-8020-6f2fe07d60fe.png)

**Comment by brx19** [comment]
Fixed as proposed in desired result.

![image](https://user-images.githubusercontent.com/23616759/45489259-1d3dc480-b764-11e8-9043-ecd416464b49.png)
