### ISSUE TITLE
Low contrast in Polly app

### ISSUE THREAD

**Issue by Smaalz** [brx19/slack-night-mode#3]
When user creates new poll, poll type dropdown list is very dark. Black on dark grey colours are used. Contrast should be increased for ease of use.

![poll type multiple choice](https://user-images.githubusercontent.com/23420519/45608291-5c189680-ba52-11e8-9649-eb3d9de6db11.png)

When adding new poll options field labels have low contrast. Text is dark grey on grey background. I think font colour should be brighter.

![poll options](https://user-images.githubusercontent.com/23420519/45608388-d5b08480-ba52-11e8-9f49-77aaf25a6e4b.png)

When adding a comment to poll option text has low contrast. I think it should be brighter.

![add comment to option](https://user-images.githubusercontent.com/23420519/45608483-6c7d4100-ba53-11e8-8d45-d877d9652489.png)

When poll is in a thread, choice buttons have low contrast. Light grey text on white background. I think the font should be darker.

![poll in a thread](https://user-images.githubusercontent.com/23420519/45608636-44421200-ba54-11e8-967d-ce3457d21d39.png)

**Comment by brx19** [comment]
All buttons have been redesigned. Issue fixed.
