### ISSUE TITLE
Adding new DM, the Tip box shows white left border

### ISSUE THREAD

**Issue by dzon2000** [brx19/slack-night-mode#4]
![image](https://user-images.githubusercontent.com/33714273/48615448-3dbb1280-e991-11e8-9a2a-62d46a6225af.png)

**Comment by brx19** [comment]
Issue is now fixed:

![image](https://user-images.githubusercontent.com/23616759/49858470-44547280-fdf5-11e8-8fe2-15bc2afd8099.png)
